### ISSUE TITLE
Sarah : Workflows : 2 weeks

### ISSUE THREAD

**Issue by SarahNaji12** [HYF-Class20/home#12]
1 Clone the class repository**

 2 Create a new branch and add a file in the ./student-bios folder:
       - important: Use your GitHub username as the name of your file. ie. colevandersWands.md 
       
        -Go all out! Take a look at this [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and [emojis list](https://gist.github.com/rxaviers/7360908) for inspiratio]

        -Make sure your code is well-formatted and all linting checks pass

  3 Push your branch to the class repository on GitHub 

  4 Open a pull request to from your branch to the main branch and assign a coach to review and merge your code
        Make sure to go through the whole PR checklist and to pass the CI checks

**Comment by bermarte** [comment]
Watch the video Tamer posted to correct your issue

**Comment by SarahNaji12** [comment]
ok

**Comment by bermarte** [comment]
@SarahNaji12 by watching the video you should be able to change your issue accordingly.
The content of your issue is not yet right. 

**This part needs to be changed**

> Clone the class repository**
>
>2 Create a new branch and add a file in the ./student-bios folder:
>- important: Use your GitHub username as the name of your file. ie. colevandersWands.md
>
 >   -Go all out! Take a look at this [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and [emojis list](https://gist.github.com/rxaviers/7360908) for inspiration]
>
>    -Make sure your code is well-formatted and all linting checks pass
>3 Push your branch to the class repository on GitHub
>
>4 Open a pull request to from your branch to the main branch and assign a coach to review and merge your code
>Make sure to go through the whole PR checklist and to pass the CI checks

**Comment by bermarte** [comment]
I see you made another issue, so I will close this one

**Comment by SarahNaji12** [comment]
Thank you
I hope it will be true this time
