### ISSUE TITLE
Takang's :Bio workflow

### ISSUE THREAD

**Issue by Takang03** [HYF-Class20/home#120]
## What went well?
- Getting help to understand git and github

## What went less well?
- Problem with npm command and laptop
## Lessons Learned
- npm command
- Git pull and git push
- Asking for help
- How to solve lint error
- Using `git pull origin main/master` to have a fresh version
## Sunday Prep Work
- Started preparing and studying for the new module

**Comment by bermarte** [comment]
You need to link the issue to the PR, in **Development**

**Comment by bermarte** [comment]
the text of the issue should be like this https://github.com/HYF-Class20/home/issues/55 I think you mixed it with the check-in issue. The Title should and the labels are a bit different, I will update it.
