### ISSUE TITLE
Betul : student's bio 

### ISSUE THREAD

**Issue by betulsancak** [HYF-Class20/home#13]
[-]([url](url)) [x] I wrote my markdown locally on a new branch
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
- [x]  [linked my PR to this issue](https://github.com/HYF-Class20/home/pull/35)

**Comment by betulsancak** [comment]
# Week 1 Check-In

## I Need Help With:


## What went well?

what do you think went will with you?

## What went less well?

what do you think went less will with you?

## Lessons Learned

what have your learned from the first week?

## Sunday Prep Work
 what have you prepared for next Sunday class?

**Comment by bermarte** [comment]
@betulsancak Assignee here is only you (so I removed me), the coaches are the reviewers (to mention in the PR like you did).
