### ISSUE TITLE
Ibrahim ali: student's bio 

### ISSUE THREAD

**Issue by Ibrahim86Ali** [HYF-Class20/home#14]
- [x] I wrote my markdown locally on a new branch
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
- [x] I
      [linked my PR to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by bermarte** [comment]
Hi @Ibrahim86Ali

https://user-images.githubusercontent.com/979362/227127507-731732ca-65ba-459c-8ef6-6d60db2963d7.mov

**Comment by bermarte** [comment]
Now, how to link issue and PR

https://user-images.githubusercontent.com/979362/227128912-079b5769-5062-42eb-8d51-1c4f0a99ed0e.mp4
