### ISSUE TITLE
Workflows :Andy :2 week

### ISSUE THREAD

**Issue by andykeshishian** [HYF-Class20/home#57]
For your group's deliverable issue in the class repo:

- [x] [repo](https://github.com/_/_)
- [x] [many small, well-named commits](https://github.com/_/_/commits)
- [x] a nice README
- [x] one well-named file per person
- [x] [one pull requests for each group member](https://github.com/_/_/pulls)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code
For your individual PRs in your group repository
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/people` according to group conventions
  - [x] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [x] created a new PR linked to this issue
  - [x] make sure all of the checks passed
  - [x] assigned someone to review and merge my PR

**Comment by talmurshidi** [comment]
This is not a check-in issue.
For what?
