### ISSUE TITLE
Your Name: module name, number of weeks in this module

### ISSUE THREAD

**Issue by emran-ai** [HYF-Class20/home#67]
Week 2

- [x] I have pushed my progress to [my fork of exercises repo](_)

## What went well?

- Everything went well

## Lessons Learned

- I have learned different command.
- like for me the command that i learned was how to restore the previous file.
- `Git log` to see the latest commit
- copy the hast code
- `git reset --head `paster Hash`
`
## Sunday Prep Work
I have reviewed all the stuff about agile board and how to use it.

<!---- BEGIN RETRO TEMPLATE: copy this into a new comment at the end of each module

### What was clear, what did you master?
I have mastered a lot like the d/f between the Github and Gitlab.

### Where can you help others moving forwards?
I would be happy to help people who don't understand how to use GitHub.

---

**Comment by samirm00** [comment]
@emran-ai  is that your `check-in` issue ???
