### ISSUE TITLE
Gabriella Lohy : Agile Development : 4 Weeks

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/home#74]
# Learning Objectives

## [0. Developing HTML & CSS](https://github.com/HackYourFutureBelgium/agile-development/blob/master/0-developing-html-and-css) </br>
Practice with the skills, tools, and workflows you will need to efficiently develop websites written with HTML & CSS.
- 🥚 VSCode: you can ...
- [x] use the LiveServer extension to launch an HTML page in the browser
- [x]  use autocomplete to begin a new HTML document, create new tags, and much more
- [x]  use the HTML CSS Support and IntelliSense fo CSS class names extensions to make writing HTML & CSS more efficient
- 🥚 Formatting HTML & CSS: 
- [x]  use VSCode configurations to format your code on save
- [x]  use `npm run format` to format all the code in your repository
- 🥚 Linting CSS: You can use the `npm run lint:css` script to find mistakes in your CSS, and you can fix the mistakes.
- 🥚 Validating HTML: You can use the `npm run validate:html` script to find mistakes in your CSS, and you can fix the mistakes.
- 🥚 Browser Developer Tools: You can ...
- [x]  inspect the source code of a web page using the Sources tab
- [ ]  find any part of the web page in the Elements tab of your Dev Tools DOM inspector
- [ ]  find the styles for any element in the Elements tab
- [ ]  make temporary changes in a web page from the Elements tab to see how they will look

## [1. Following Plans](https://github.com/HackYourFutureBelgium/agile-development/blob/master/1-following-plans) </br>
Practice working together in a group to build small websites in incremental steps according to a plan. You will be given final code, a detailed plan to rebuild it, and will need to work as a group following the processes in [Planning and Collaborating](https://github.com/HackYourFutureBelgium/planning-and-collaborating).
- [x]  🥚 Project Definition and Scope: As a group, you can agree on what you are trying to build, and can clearly describe the project using a README and a repository description. 
- [x] 🥚 Project Constraints: As a group you can define project constraints by discussing your strengths, weaknesses and context. You can set these types of constraints:
- [x]  External: constraints that come from outside your group
- [x]  Internal, Involuntary: constraints that come from within your group, but your group did not decide to have.
- [x]  Internal, Voluntary: constraints your group decides on to improve the quality of your development process and final software.
- [x]  🥚 Communication Plans: You can work with your group mates to agree on a communication plan to follow during development.
- [x]  🥚 Communicating Challenges: During development you can discuss with your group when ...
- you are blocked and need help the agreed channels of communication.
- your schedule or availability changes
- you are having trouble getting along with each other
- [x]  🥚 Using a Backlog: You can develop from a backlog of features organized by priority:
- must-have
- should-have
- could-have
- [x]  🥚 Follow a Development Strategies: You can follow a development strategy to understand the code required for must-have user stories.
- [x]  🥚 Create Issues From a Dev Strategy: You can create issues for user stories in your project based on the development strategy.
- [x]  🥚 Retrospective: Your group can complete a retrospective to ...
- [x]  assess how well you worked as a group
- [ ]  find ways to improve in the next project
- [ ]  compare your plan to the reality of developing your website
- [x]  🐣 Claiming and Completing Issues: You can claim issues from the TODO column of a project board and ...
- [x]  track your progress with the project board
- [x]  develop your code locally on a separate branch
- [x]  send a PR that passes CI checks and meets the requirements
- [x]  🐣 Code Review: You can both review a group mate's PR, and productively participate in a review of your own code.
- [ ]  🐣 Match a Design & Acceptance Criteria: When developing your tasks, you can write code that matches the project's Wireframe and meets your issue's Acceptance Criteria.

## [2. Writing Plans](https://github.com/HackYourFutureBelgium/agile-development/blob/master/2-writing-plans) </br>
Practicing writing your own plans as a group. You will be given only the final code for HTML/CSS web pages, your group will need write a detailed plan for rebuilding the website in small steps.
- [x]  🥚 **Write User Personas**: As a group you can describing your site's users with User Personas, and you can use the personas to plan your website from the user's perspective.
- [x]  🥚 **Write User Stories**: Given a working web page, you can describe it with user stories and acceptance criteria for each user story.
- [x] 🐣 **Write a Backlog**: After listing all the user stories for a web page, you can organize them into a Backlog by priority: must-have, should-have and could-have
- [x]  🐣 **Create a Prioritized Design**: Using your backlog and the original site as a guide, you can create a Wireframe of the site your group will build. You can use different colors and comments to indicate a priority for each component in the Wireframe.
- [x]  🐣 **Write a Development Strategies**: You can translate your Wireframe and Backlog into a Development Strategy for the must-have user stories.

## [3. Adapting Plans](https://github.com/HackYourFutureBelgium/agile-development/blob/master/3-adapting-plans) </br>
Even the best plans are not perfect, it's not possible to know everything ahead of time! You may be able to plan everything ahead of time when the web pages you build are very small and you have the code ahead of time, but it's a whole different thing when you need to build a larger web page over a longer period of time.

In this chapter you will practice full Agile Development by developing a larger, open-ended web pages and adapting your plans as you go. Your team will need to make an initial plan, but the plan will change! Practice having regular meetings with your group to review the website's progress, review your plan, and make any changes in the plan that are necessary to keep the project on schedule.
- [ ]  🐣 Adjusting the Backlog: As a group you can agree to changes in the backlog when necessary.
- [ ]  🐣 Adjusting the Design: As a group you can agree on changes to the design during the development process when it becomes clear your old design needs updating.
- [ ]  🐣 Updating the Project Board: You can manage the project board by adding, removing or updating issues when necessary. This includes changing labels, milestones, or assignees when necessary.
------
## AGILE (4 weeks)
- [x] Understanding AGILE
Agile is a about teamwork! We create small circle to achieve the project goal. Agile is flexible because it's build with small steps. Different with waterfall method in agile if we need to make any changes we still can go back to the previous step. In waterfall method the project needs to be break down in order to make any changes. 
------

# Week 1 (April 2nd, 2023)

- [ ] I have pushed my progress to [my fork of exercises repo](_)

## I Need Help With:
Nothing for a moment

## I Needed Help With: (Problem solved with coaches guidance. THANK YOU!!)
- I cloned our group repo but when I ran a syntax the system told me that it’s not a git repository.
Searched the solution on chatGPT, it says I need to ran `git init`. I did it.
Then I ran `git pull origin main` it told me that the origin doesn’t appear as git repo.
I ran `git status` just to check and it shows an untracked files.
I asked chatGPT, it says I need to `git add agile-development-group2-all-about-trees/` and commit.
But I’m on master branch, my question was: What should I do? May I run the code on master branch?

Tamer helped me locating the error and gave solution: THANKS!
>If you will write pwd you will notice that you are not inside the project repo.
You still have to write `cd agile-development-group2-all-about-trees`
Now you have a problem after using `git init` because now you have nested repos.
Please delete the folder and clone it again and make sure you are in the correct path.
Delete Agile-Group2 too

![Screenshot 2023-04-02 at 21 37 36](https://user-images.githubusercontent.com/124396156/229685325-306d8590-897f-46d2-bc3a-11ef2489eefe.png)

- Bermarte and Tamer helped me with a complicated (for me it's complicated) vscode conflict.

## What went well?
- [x] Creating user persona
- [x] Dividing task in the group

## What went less well?
Communication with some group members on slack

## Lessons Learned
- [x] Always make sure for the correct path to work
- [x] Understanding AGILE
- [x] Naming conventions
   - Camel case
   - Snack case
   - Kebab case
   - Pascal case
 
**Agile Methods**
- [x] Requirement definition & analysis of concept
- [x] Planning of sprint
- [x] Collaborative design development
- [x] Create & implement
- [x] Review & monitor
   
**Agile Methodology**
- [x] **User persona** an imaginary audience. It helps us to understanding the targeted group audience. Without user persona we can't make wireframe.
- [x] **User stories/backlog** is sorted by PRIORITY! It contains needs of the audience. Must have, Should have and Could have.
- [x] **Acceptance criteria** example: A user can't submit a form without completing all mandatory
- [x] **Wireframe** must be create based on user story/backlog. 
- [x] **Development strategy** converting the must have or priority needs of audience to coding phase.
- [x] **Retrospective** intern feedback in group. It's about BEHAVIOR not people. We are not allowed to pointing someone in this session. Mostly done at the end of the week. 
- [x] **Stand-up meeting** is a brief daily meeting. It's like updating our work project to the group, what we've done, what we are currently busy with or even which problem do we have about the task. Mostly done for max 15mins
- [x] **Constraints** consist of planning, availability timetable, template file, code of conduct.

**Planning**
- [x] Make a group availability timetable
- [x] Set-up meeting hours for the whole week based on availability timetable
- [x] Creating repo using template
- [x] Protecting master repo
- [x] Set the repo live/live url
- [x] Adding collaborator
- [x] Creating additional labels
- [x] Creating Project Board and organising it
- [x] Creating issue to be put in PB
- [x] Discussing README content
- [x] Discussing code of conduct
- [x] Discussing user persona
- [x] Discussing backlog
- [x] Discussing design
- [x] Creating wireframe
- [x] Retrospective

## Sunday Prep Work

- [x] Watching youtube tutorial about Loruki
- [x] Reading [User Centered Development](https://github.com/HackYourFutureBelgium/agile-development/blob/master/lesson-plans/user-centered-development.md) and [Loruki Rebuild Deliverable](https://github.com/HackYourFutureBelgium/agile-development/blob/master/deliverables/loruki-rebuild.md)

---
# Week 2 (April 9th, 2023)

## I Need Help With:
Nothing for a moment

## I Needed Help With: (Problem solved with coaches guidance. THANK YOU!!)
- I created a branch for user personas, `git pull origin master`, doing user personas things in it, done, PR.
After that I made a new branch for Backlog. `git pull origin master`, doing backlog in it, nothing else, done, before push I did git status and its shows that I only modified Backlog, git add, commit, PR. 
But,,, on my Backlog PR it shows my commit about creating user persona which I didn’t do using Backlog branch. 

My question was: 
Is it because I still have a user personas PR and do `git pull origin master` on branch Backlog? 
But the user personas PR haven’t merge yet.

Tamer helped me to understand the situation. He asked me to try running a syntax `git log --first-parent`.
Apparently I created nested branches. 

I didn't know that if we want to create a new branch, we need to go to `master branch` first and create a branch from there.
My fault was that I created a branch directly from user personas branch with syntax `git checkout -b backlog` 

Solution I made was to deleted the nested branch; backlog, and create a new branch from the master.

Here's the screenshot of `git log --first-parent` result :
![Screenshot 2023-04-10 at 02 29 26](https://user-images.githubusercontent.com/124396156/231434255-0d71846e-a00e-42f7-97a1-586156845386.png)

## What went well?
Everything

## What went less well?
Nothing for a moment

## Lessons Learned 
**Always** make branch from master branch!

**Writing Plans**
- [x] Write all `planning` phase and make a brief presentation on Sunday class. We chose **`NETFLIX`** as our project

**New syntax** 
- [x] `npm run lint:css`  ===> To check CSS code quality
- [x] `npm run validate:html`  ===> To check HTML code quality
- [x] `git log --first-parent`
![Screenshot 2023-04-12 at 13 05 39](https://user-images.githubusercontent.com/124396156/231439434-776b038c-dc08-444b-9755-f420329980b3.png)

## Sunday Prep Work
I haven't really study yet, just briefly read [Being Agile](https://github.com/HackYourFutureBelgium/agile-development/blob/master/lesson-plans/being-agile.md) and [deliverable](https://github.com/HackYourFutureBelgium/agile-development/blob/master/deliverables/hyf-redesign.md) for next week. 
Currently I am still busy with **`Loruki Rebuild`** task

**Comment by samirm00** [comment]
@GabriellaLohy  well, because when you clone a repo, you need to `cd` into the repo and then open it with your VScode `code . `

**Comment by samirm00** [comment]
@GabriellaLohy  you always need to create branches for `master` / `main` because when you create a branch you will need a full copy of what you have on `GitHub`, which will be on the `master`/`main` when you do `git pull` then you can create a new branch which will have the latest update.

**Comment by samirm00** [comment]
Ok, using `git pull origin master will bring the changes from `GitHub` merge it to the local master branch and then update your `branch` so no you don't need to checkout master and do `git pull`

**Comment by GabriellaLohy** [comment]
@samirm00 Ahh ok.. Thanks a lot Samir..

**Comment by samirm00** [comment]
@GabriellaLohy  Actually I was wrong, when you do `git pull origin master` , the changes on GitHub master will merge into your current branch only. so you will need to checkout master and do `git pull`. My bad.

**Comment by GabriellaLohy** [comment]
@samirm00 Aha! Noted! Thanks Samir!

**Comment by GabriellaLohy** [comment]
@talmurshidi Noted! ✅ Thank you Tamer 🙏🏼
